In [1]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [4]:
movies=movies.merge(credits,on='title')

In [5]:
movies=movies[['movie_id','title','keywords','genres','overview','cast','crew']]

In [6]:
movies.head(4)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   keywords  4809 non-null   object
 3   genres    4809 non-null   object
 4   overview  4806 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [9]:
type(movies.iloc[0].genres)

str

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
overview    0
cast        0
crew        0
dtype: int64

In [12]:
type(movies.iloc[0].genres)

str

In [13]:
import ast
movies['keywords']=movies['keywords'].apply(lambda x:ast.literal_eval(x))

In [14]:
type(movies.iloc[0].keywords)

list

In [15]:
movies['genres']=movies['genres'].apply(lambda x:ast.literal_eval(x))
movies['cast']=movies['cast'].apply(lambda x:ast.literal_eval(x))
movies['crew']=movies['crew'].apply(lambda x:ast.literal_eval(x))

In [16]:
type(movies.iloc[0].genres)

list

In [17]:
movies.iloc[0].genres

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [18]:
def convert(List):
    L=[]
    for i in List:
        L.append(i['name'])
        
    return L

In [19]:
movies.loc[:,'genres']=movies['genres'].apply(convert)

In [20]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [18]:
movies=movies[movies['genres'].apply(lambda x:x!=[])]
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4803                              [Foreign, Thriller]
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4808                                    [Documentary]
Name: genres, Length: 4778, dtype: object

In [21]:
movies.head(3)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{'id': 1463, 'name': 'culture clash'}, {'id':...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
1,285,Pirates of the Caribbean: At World's End,"[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4232c3a36847f800b579', 'de..."
2,206647,Spectre,"[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...","[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '54805967c3a36829b5002c41', 'de..."

In [20]:
movies.iloc[0].keywords

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [22]:
movies.loc[:, 'keywords'] = movies['keywords'].apply(convert)
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [22]:
movies=movies[movies['keywords'].apply(lambda x:x!=[])]
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4801     [gang, audition, police fake, homeless, actress]
4802    [distrust, garage, identity crisis, time trave...
4804    [united states–mexico barrier, legs, arms, pap...
4806    [date, love at first sight, narration, investi...
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4393, dtype: object

In [33]:
movies.iloc[0].cast

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [23]:
def castCon(list1):
    c=0
    L=[]
    for i in list1:
        if c!=4:
            L.append(i['name'])
            c=c+1
        else:
            break
            
    return L

In [24]:
movies.loc[:,'cast']=movies['cast'].apply(castCon)
movies['cast']

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [37]:
movies.iloc[0].crew

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [25]:
def convertCrew(list2):
    L=[]
    for i in list2:
        if i['job']=='Director':
            L.append(i['name'])
            break
            
    return L

In [26]:
movies.loc[:,'crew']=movies['crew'].apply(convertCrew)
movies['crew']

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [40]:
movies.head(3)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]

In [41]:
type(movies.iloc[0].overview)

str

In [27]:
movies['overview']=movies['overview'].apply(lambda x:[x])
movies['overview']

0       [In the 22nd century, a paraplegic Marine is d...
1       [Captain Barbossa, long believed to be dead, h...
2       [A cryptic message from Bond’s past sends him ...
3       [Following the death of District Attorney Harv...
4       [John Carter is a war-weary, former military c...
                              ...
4804    [El Mariachi just wants to play his guitar and...
4805    [A newlywed couple's honeymoon is upended by t...
4806    ["Signed, Sealed, Delivered" introduces a dedi...
4807    [When ambitious New York attorney Sam is sent ...
4808    [Ever since the second grade when he first saw...
Name: overview, Length: 4806, dtype: object

In [43]:
movies.head(4)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[In the 22nd century, a paraplegic Marine is d...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Captain Barbossa, long believed to be dead, h...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",[A cryptic message from Bond’s past sends him ...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",[Following the death of District Attorney Harv...,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]

In [28]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [45]:
movies.head(4)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In the 22nd century, a paraplegic Marine is d...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain Barbossa, long believed to be dead, h...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]",[A cryptic message from Bond’s past sends him ...,"[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]",[Following the death of District Attorney Harv...,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]

In [29]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [30]:
new_df=movies[['movie_id','title','tags']]
new_df

,movie_id,title,tags
0,19995,Avatar,"[In the 22nd century, a paraplegic Marine is d..."
1,285,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h..."
2,206647,Spectre,[A cryptic message from Bond’s past sends him ...
3,49026,The Dark Knight Rises,[Following the death of District Attorney Harv...
4,49529,John Carter,"[John Carter is a war-weary, former military c..."
...,...,...,...
4804,9367,El Mariachi,[El Mariachi just wants to play his guitar and...
4805,72766,Newlyweds,[A newlywed couple's honeymoon is upended by t...
4806,231617,"Signed, Sealed, Delivered","[""Signed, Sealed, Delivered"" introduces a dedi..."
4807,126186,Shanghai Calling,[When ambitious New York attorney Sam is sent ...
4808,25975,My Date with Drew,[Ever since the second grade when he first saw...

In [31]:
new_df.loc[:,'tags']=new_df['tags'].apply(lambda x:x[0])

In [49]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [32]:
new_df.loc[:,'tags']=new_df['tags'].apply(lambda x:x.lower())

In [51]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [33]:
new_df.to_csv('tmdb5kPrePData.csv',index=False)

In [38]:
new_df[new_df['title']=='Avatar'].movie_id[0]

19995

In [ ]:
def checkIf(name):
    if new_df['title']==name:
        return new_df[new_df['title']=='Avatar'].movie_id[0]
    else:
        print('not f')

In [52]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer

In [53]:
ps=PorterStemmer()
stop_words=set(stopwords.words('english'))

In [54]:
def removingSWandDual(obj):
    word_tokens=word_tokenize(obj)
    filter_sen=[w for w in word_tokens if not w.lower() in stop_words]
    remov_d_text=[ps.stem(w) for w in filter_sen]
    return ' '.join(remov_d_text)

In [55]:
new_df.loc[:,'tags']=new_df['tags'].apply(removingSWandDual)

In [56]:
new_df['tags']

0       22nd centuri , parapleg marin dispatch moon pa...
1       captain barbossa , long believ dead , come bac...
2       cryptic messag bond ’ past send trail uncov si...
3       follow death district attorney harvey dent , b...
4       john carter war-weari , former militari captai...
                              ...
4804    el mariachi want play guitar carri famili trad...
4805    newlyw coupl 's honeymoon upend arriv respect ...
4806    `` sign , seal , deliv '' introduc dedic quart...
4807    ambiti new york attorney sam sent shanghai ass...
4808    ever sinc second grade first saw e.t . extrate...
Name: tags, Length: 4806, dtype: object

In [57]:
new_df

,movie_id,title,tags
0,19995,Avatar,"22nd centuri , parapleg marin dispatch moon pa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa , long believ dead , come bac..."
2,206647,Spectre,cryptic messag bond ’ past send trail uncov si...
3,49026,The Dark Knight Rises,"follow death district attorney harvey dent , b..."
4,49529,John Carter,"john carter war-weari , former militari captai..."
...,...,...,...
4804,9367,El Mariachi,el mariachi want play guitar carri famili trad...
4805,72766,Newlyweds,newlyw coupl 's honeymoon upend arriv respect ...
4806,231617,"Signed, Sealed, Delivered","`` sign , seal , deliv '' introduc dedic quart..."
4807,126186,Shanghai Calling,ambiti new york attorney sam sent shanghai ass...
4808,25975,My Date with Drew,ever sinc second grade first saw e.t . extrate...

In [58]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)

In [59]:
vectorized_array = cv.fit_transform(new_df['tags']).toarray()

In [60]:
vectorized_array[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
feature_names = cv.get_feature_names_out()

In [62]:
feature_names

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooey'], dtype=object)

In [74]:
from sklearn.metrics.pairwise import cosine_similarity

In [75]:
similarity=cosine_similarity(vectorized_array)

In [76]:
similarity.shape

(4806, 4806)

In [77]:
similarity[119]

array([0.        , 0.0496904 , 0.03928371, ..., 0.05498574, 0.02807173,
       0.03042903])

In [78]:
new_df.head(4)

,movie_id,title,tags
0,19995,Avatar,"22nd centuri , parapleg marin dispatch moon pa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa , long believ dead , come bac..."
2,206647,Spectre,cryptic messag bond ’ past send trail uncov si...
3,49026,The Dark Knight Rises,"follow death district attorney harvey dent , b..."

In [79]:
new_df[new_df['title']=='Avatar'].movie_id[0]

19995

In [80]:
movie_index=new_df[new_df['title']=='Batman Begins'].index[0]
movie_index

119

In [82]:
movie_index = new_df[new_df['title'] == 'Batman Begins'].index[0]
similarities_to_batman_begins = similarity[movie_index]  # Assuming 'similarity' is a numpy array

# Enumerate over the similarity scores
similar_movies_with_scores = list(enumerate(similarities_to_batman_begins))

# Sort by similarity in descending order and get the top 5 similar movies
top_similar_movies = sorted(similar_movies_with_scores, reverse=True, key=lambda x: x[1])[1:6]
top_similar_movies

[(2252, 0.2581988897471611),
 (962, 0.2321035412742638),
 (299, 0.19096396641051547),
 (2644, 0.1887128390240993),
 (1362, 0.18670401120373464)]

In [84]:
similarities_to_batman_begins

array([0.        , 0.0496904 , 0.03928371, ..., 0.05498574, 0.02807173,
       0.03042903])

In [83]:
similar_movies_with_scores

[(0, 0.0),
 (1, 0.049690399499995326),
 (2, 0.03928371006591931),
 (3, 0.18332398030762342),
 (4, 0.0),
 (5, 0.032075014954979206),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.15609763526361567),
 (10, 0.0),
 (11, 0.03253000243161777),
 (12, 0.05337605126836238),
 (13, 0.0),
 (14, 0.03928371006591931),
 (15, 0.06327719971683327),
 (16, 0.0),
 (17, 0.030055654488914414),
 (18, 0.023870495801314433),
 (19, 0.0),
 (20, 0.02222222222222222),
 (21, 0.03849001794597506),
 (22, 0.0),
 (23, 0.0),
 (24, 0.041030496993110906),
 (25, 0.021931723165325632),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.025949964805384102),
 (30, 0.06506000486323554),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.09938079899999065),
 (36, 0.0),
 (37, 0.0),
 (38, 0.09548198320525773),
 (39, 0.0),
 (40, 0.0),
 (41, 0.029695693545824933),
 (42, 0.03300491809922247),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0501097352001886),
 (46, 0.0),
 (47, 0.07647191129018727),
 (48, 0.026189140043946204),
 (49, 0.03849001794597506),
 (50, 0.0),
 (51, 0.022371868507134147),
 (52, 0.0),
 (53, 0.030816677568068284),
 (54, 0.0),
 (55, 0.0),
 (56, 0.049690399499995326),
 (57, 0.030055654488914414),
 (58, 0.02868876552746235),
 (59, 0.0),
 (60, 0.0),
 (61, 0.051434449987363975),
 (62, 0.12171612389003693),
 (63, 0.0),
 (64, 0.04667600280093366),
 (65, 0.18257418583505539),
 (66, 0.15408338784034142),
 (67, 0.0),
 (68, 0.10286889997472795),
 (69, 0.03792534159923829),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (74, 0.03253000243161777),
 (75, 0.0),
 (76, 0.036369648372665396),
 (77, 0.13938889959715112),
 (78, 0.0),
 (79, 0.09622504486493762),
 (80, 0.0),
 (81, 0.019341961772855316),
 (82, 0.04536092116265145),
 (83, 0.0),
 (84, 0.0),
 (85, 0.041030496993110906),
 (86, 0.0),
 (87, 0.0),
 (88, 0.0),
 (89, 0.0),
 (90, 0.04415107856883479),
 (91, 0.0),
 (92, 0.06700252101728081),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.041030496993110906),
 (97, 0.0890870806374748),
 (98, 0.10286889997472795),
 (99, 0.0),
 (100, 0.0),
 (101, 0.07407407407407408),
 (102, 0.0),
 (103, 0.06163335513613657),
 (104, 0.0),
 (105, 0.051434449987363975),
 (106, 0.0),
 (107, 0.0549857399228215),
 (108, 0.06804138174397717),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (112, 0.03928371006591931),
 (113, 0.0),
 (114, 0.0),
 (115, 0.034020690871988585),
 (116, 0.09016696346674324),
 (117, 0.0),
 (118, 0.0),
 (119, 1.0000000000000004),
 (120, 0.07548513560963972),
 (121, 0.0),
 (122, 0.049690399499995326),
 (123, 0.04536092116265145),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (127, 0.049690399499995326),
 (128, 0.04199605255658081),
 (129, 0.0),
 (130, 0.10369516947304253),
 (131, 0.033501260508640406),
 (132, 0.0573775310549247),
 (133, 0.0),
 (134, 0.0),
 (135, 0.0),
 (136, 0.09759000729485331),
 (137, 0.05832118435198043),
 (138, 0.0),
 (139, 0.10540925533894599),
 (140, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.02749286996141075),
 (144, 0.0),
 (145, 0.026435052857271473),
 (146, 0.046373889576016826),
 (147, 0.03573708449459316),
 (148, 0.0),
 (149, 0.0),
 (150, 0.0),
 (151, 0.0),
 (152, 0.04667600280093366),
 (153, 0.0),
 (154, 0.0),
 (155, 0.0),
 (156, 0.03163859985841663),
 (157, 0.05337605126836238),
 (158, 0.0),
 (159, 0.0),
 (160, 0.08948747402853659),
 (161, 0.0),
 (162, 0.0),
 (163, 0.03513641844631533),
 (164, 0.0),
 (165, 0.049690399499995326),
 (166, 0.03928371006591931),
 (167, 0.0),
 (168, 0.06700252101728081),
 (169, 0.0),
 (170, 0.06011130897782883),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.11547005383792516),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.06913011298202835),
 (179, 0.0),
 (180, 0.06804138174397717),
 (181, 0.0),
 (182, 0.030816677568068284),
 (183, 0.026435052857271473),
 (184, 0.06243905410544627),
 (185, 0.03928371006591931),
 (186, 0.0),
 (187, 0.0),
 (188, 0.053896805563629545),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.033501260508640406),
 (193, 0.07053456158585983),
 (194, 0.06415002990995841),
 (195, 0.04199605255658081),
 (196, 0.14433756729740643),
 (197, 0.06163335513613657),
 (198, 0.04536092116265145),
 (199, 0.0),
 (200, 0.07856742013183862),
 (201, 0.049690399499995326),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.09938079899999065),
 (206, 0.08333333333333334),
 (207, 0.0),
 (208, 0.0),
 (209, 0.09938079899999065),
 (210, 0.1382602259640567),
 (211, 0.0),
 (212, 0.12171612389003693),
 (213, 0.0),
 (214, 0.0),
 (215, 0.07273929674533079),
 (216, 0.0),
 (217, 0.027777777777777783),
 (218, 0.060858061945018464),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.023870495801314433),
 (223, 0.0),
 (224, 0.06189844605901729),
 (225, 0.13608276348795434),
 (226, 0.04303314829119352),
 (227, 0.0),
 (228, 0.0),
 (229, 0.02151657414559676),
 (230, 0.024246432248443594),
 (231, 0.028375217691958287),
 (232, 0.049690399499995326),
 (233, 0.0),
 (234, 0.03513641844631533),
 (235, 0.0),
 (236, 0.0),
 (237, 0.04415107856883479),
 (238, 0.12858612496840993),
 (239, 0.04928141806363819),
 (240, 0.03703703703703704),
 (241, 0.034020690871988585),
 (242, 0.07273929674533079),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0949157995752499),
 (247, 0.0),
 (248, 0.03253000243161777),
 (249, 0.0),
 (250, 0.03928371006591931),
 (251, 0.0),
 (252, 0.09128709291752769),
 (253, 0.027777777777777783),
 (254, 0.0),
 (255, 0.03513641844631533),
 (256, 0.0),
 (257, 0.0),
 (258, 0.04057204129667897),
 (259, 0.049690399499995326),
 (260, 0.0),
 (261, 0.041030496993110906),
 (262, 0.034020690871988585),
 (263, 0.0),
 (264, 0.05869672708837492),
 (265, 0.030816677568068284),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (272, 0.036369648372665396),
 (273, 0.02868876552746235),
 (274, 0.0),
 (275, 0.0),
 (276, 0.055555555555555566),
 (277, 0.0),
 (278, 0.03300491809922247),
 (279, 0.0),
 (280, 0.0),
 (281, 0.0),
 (282, 0.04199605255658081),
 (283, 0.11785113019775793),
 (284, 0.0),
 (285, 0.044743737014268294),
 (286, 0.17609018126512477),
 (287, 0.0),
 (288, 0.04667600280093366),
 (289, 0.07453559924999299),
 (290, 0.0),
 (291, 0.0),
 (292, 0.04667600280093366),
 (293, 0.0),
 (294, 0.0),
 (295, 0.0),
 (296, 0.12487810821089254),
 (297, 0.0),
 (298, 0.08606629658238704),
 (299, 0.19096396641051547),
 (300, 0.0),
 (301, 0.0),
 (302, 0.06243905410544627),
 (303, 0.03774256780481986),
 (304, 0.017495462702715934),
 (305, 0.0),
 (306, 0.0),
 (307, 0.0365331082900794),
 (308, 0.0),
 (309, 0.0),
 (310, 0.02222222222222222),
 (311, 0.0),
 (312, 0.03163859985841663),
 (313, 0.04415107856883479),
 (314, 0.0),
 (315, 0.03774256780481986),
 (316, 0.030816677568068284),
 (317, 0.0),
 (318, 0.0),
 (319, 0.048112522432468816),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.034020690871988585),
 (324, 0.08703882797784893),
 (325, 0.04303314829119352),
 (326, 0.0),
 (327, 0.0),
 (328, 0.07548513560963972),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.0),
 (333, 0.07698003589195011),
 (334, 0.034020690871988585),
 (335, 0.0),
 (336, 0.0),
 (337, 0.029012942659282975),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.03573708449459316),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.025717224993681988),
 (346, 0.0),
 (347, 0.031219527052723135),
 (348, 0.08399210511316162),
 (349, 0.05337605126836238),
 (350, 0.03163859985841663),
 (351, 0.07027283689263066),
 (352, 0.0),
 (353, 0.025949964805384102),
 (354, 0.10050378152592121),
 (355, 0.08512565307587486),
 (356, 0.04667600280093366),
 (357, 0.0),
 (358, 0.0),
 (359, 0.11785113019775793),
 (360, 0.034020690871988585),
 (361, 0.0),
 (362, 0.04536092116265145),
 (363, 0.053896805563629545),
 (364, 0.0),
 (365, 0.0),
 (366, 0.03300491809922247),
 (367, 0.0),
 (368, 0.0),
 (369, 0.0),
 (370, 0.041030496993110906),
 (371, 0.06327719971683327),
 (372, 0.0),
 (373, 0.0),
 (374, 0.023168268228563865),
 (375, 0.053896805563629545),
 (376, 0.09128709291752769),
 (377, 0.05337605126836238),
 (378, 0.0),
 (379, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.06327719971683327),
 (387, 0.0),
 (388, 0.0),
 (389, 0.041030496993110906),
 (390, 0.0),
 (391, 0.051434449987363975),
 (392, 0.040128617695256406),
 (393, 0.034020690871988585),
 (394, 0.03573708449459316),
 (395, 0.06913011298202835),
 (396, 0.03774256780481986),
 (397, 0.07273929674533079),
 (398, 0.02934836354418746),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.06700252101728081),
 (403, 0.06011130897782883),
 (404, 0.048112522432468816),
 (405, 0.04303314829119352),
 (406, 0.0),
 (407, 0.02721655269759087),
 (408, 0.0),
 (409, 0.06804138174397717),
 (410, 0.0),
 (411, 0.032075014954979206),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.052870105714542946),
 (416, 0.04536092116265145),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.030055654488914414),
 (421, 0.0),
 (422, 0.0),
 (423, 0.14294833797837264),
 (424, 0.02868876552746235),
 (425, 0.0),
 (426, 0.040128617695256406),
 (427, 0.0),
 (428, 0.16972502573910517),
 (429, 0.04536092116265145),
 (430, 0.07147416898918632),
 (431, 0.0),
 (432, 0.032075014954979206),
 (433, 0.0),
 (434, 0.0),
 (435, 0.048112522432468816),
 (436, 0.030055654488914414),
 (437, 0.07273929674533079),
 (438, 0.03253000243161777),
 (439, 0.04199605255658081),
 (440, 0.02934836354418746),
 (441, 0.0),
 (442, 0.0),
 (443, 0.03300491809922247),
 (444, 0.06243905410544627),
 (445, 0.0),
 (446, 0.03849001794597506),
 (447, 0.0),
 (448, 0.0561434614044346),
 (449, 0.0),
 (450, 0.12326671027227314),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (457, 0.03456505649101418),
 (458, 0.023688968483956713),
 (459, 0.0),
 (460, 0.0),
 (461, 0.03774256780481986),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.048112522432468816),
 (466, 0.04536092116265145),
 (467, 0.0),
 (468, 0.0),
 (469, 0.0),
 (470, 0.0),
 (471, 0.031219527052723135),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (476, 0.040128617695256406),
 (477, 0.0),
 (478, 0.0280717307022173),
 (479, 0.022371868507134147),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.12038585308576921),
 (486, 0.019744962591969745),
 (487, 0.0),
 (488, 0.020752426878823012),
 (489, 0.0),
 (490, 0.0),
 (491, 0.030055654488914414),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (495, 0.0),
 (496, 0.04888237167378443),
 (497, 0.03774256780481986),
 (498, 0.0),
 (499, 0.03573708449459316),
 (500, 0.03573708449459316),
 (501, 0.03163859985841663),
 (502, 0.06163335513613657),
 (503, 0.03513641844631533),
 (504, 0.051434449987363975),
 (505, 0.0),
 (506, 0.12171612389003693),
 (507, 0.02868876552746235),
 (508, 0.0),
 (509, 0.05802588531856595),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.026189140043946204),
 (518, 0.028375217691958287),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.09622504486493762),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.0),
 (530, 0.09335200560186732),
 (531, 0.0561434614044346),
 (532, 0.06163335513613657),
 (533, 0.04536092116265145),
 (534, 0.0),
 (535, 0.0),
 (536, 0.0),
 (537, 0.0),
 (538, 0.0),
 (539, 0.0),
 (540, 0.06163335513613657),
 (541, 0.07647191129018727),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.06700252101728081),
 (549, 0.0),
 (550, 0.0),
 (551, 0.029012942659282975),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.04057204129667897),
 (556, 0.040128617695256406),
 (557, 0.0),
 (558, 0.0),
 (559, 0.0),
 (560, 0.019849711139180454),
 (561, 0.0),
 (562, 0.0),
 (563, 0.030816677568068284),
 (564, 0.0),
 (565, 0.026948402781814772),
 (566, 0.06243905410544627),
 (567, 0.03253000243161777),
 (568, 0.04199605255658081),
 (569, 0.0573775310549247),
 (570, 0.05802588531856595),
 (571, 0.029695693545824933),
 (572, 0.0),
 (573, 0.0),
 (574, 0.029695693545824933),
 (575, 0.03703703703703704),
 (576, 0.11547005383792516),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0280717307022173),
 (581, 0.03774256780481986),
 (582, 0.06700252101728081),
 (583, 0.033501260508640406),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (588, 0.0),
 (589, 0.0),
 (590, 0.04415107856883479),
 (591, 0.03703703703703704),
 (592, 0.03300491809922247),
 (593, 0.026948402781814772),
 (594, 0.0),
 (595, 0.0),
 (596, 0.02721655269759087),
 (597, 0.03849001794597506),
 (598, 0.060858061945018464),
 (599, 0.018024602347862507),
 (600, 0.0),
 (601, 0.020515248496555453),
 (602, 0.030816677568068284),
 (603, 0.0),
 (604, 0.0),
 (605, 0.06327719971683327),
 (606, 0.048112522432468816),
 (607, 0.07715167498104597),
 (608, 0.0),
 (609, 0.0),
 (610, 0.021931723165325632),
 (611, 0.029695693545824933),
 (612, 0.030055654488914414),
 (613, 0.0),
 (614, 0.0),
 (615, 0.048112522432468816),
 (616, 0.0),
 (617, 0.0),
 (618, 0.033501260508640406),
 (619, 0.06415002990995841),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.05443310539518174),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.051434449987363975),
 (628, 0.03849001794597506),
 (629, 0.028375217691958287),
 (630, 0.06415002990995841),
 (631, 0.0),
 (632, 0.0),
 (633, 0.0),
 (634, 0.0),
 (635, 0.06700252101728081),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.030429030972509232),
 (640, 0.0),
 (641, 0.0),
 (642, 0.055555555555555566),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.06913011298202835),
 (647, 0.0),
 (648, 0.0),
 (649, 0.05802588531856595),
 (650, 0.0),
 (651, 0.08247860988423225),
 (652, 0.021931723165325632),
 (653, 0.0),
 (654, 0.029012942659282975),
 (655, 0.0),
 (656, 0.0),
 (657, 0.042766686606638946),
 (658, 0.06600983619844494),
 (659, 0.03573708449459316),
 (660, 0.0),
 (661, 0.055555555555555566),
 (662, 0.03513641844631533),
 (663, 0.03928371006591931),
 (664, 0.08025723539051281),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.07273929674533079),
 (670, 0.0),
 (671, 0.0),
 (672, 0.08399210511316162),
 (673, 0.03456505649101418),
 (674, 0.11878277418329973),
 (675, 0.059391387091649865),
 (676, 0.03456505649101418),
 (677, 0.0),
 (678, 0.0),
 (679, 0.020064308847628203),
 (680, 0.03300491809922247),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.0),
 (685, 0.0),
 (686, 0.04303314829119352),
 (687, 0.0),
 (688, 0.0),
 (689, 0.06600983619844494),
 (690, 0.0),
 (691, 0.040128617695256406),
 (692, 0.0),
 (693, 0.0),
 (694, 0.06600983619844494),
 (695, 0.051434449987363975),
 (696, 0.05802588531856595),
 (697, 0.08606629658238704),
 (698, 0.0),
 (699, 0.0),
 (700, 0.0),
 (701, 0.0),
 (702, 0.0),
 (703, 0.0700140042014005),
 (704, 0.0),
 (705, 0.030429030972509232),
 (706, 0.03253000243161777),
 (707, 0.0),
 (708, 0.03456505649101418),
 (709, 0.04774099160262887),
 (710, 0.026189140043946204),
 (711, 0.08830215713766958),
 (712, 0.0890870806374748),
 (713, 0.0),
 (714, 0.0),
 (715, 0.0),
 (716, 0.0),
 (717, 0.04774099160262887),
 (718, 0.0),
 (719, 0.0),
 (720, 0.041030496993110906),
 (721, 0.04303314829119352),
 (722, 0.02668802563418119),
 (723, 0.03163859985841663),
 (724, 0.07548513560963972),
 (725, 0.0),
 (726, 0.07548513560963972),
 (727, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.03792534159923829),
 (731, 0.0),
 (732, 0.06327719971683327),
 (733, 0.0),
 (734, 0.032075014954979206),
 (735, 0.0280717307022173),
 (736, 0.0),
 (737, 0.05337605126836238),
 (738, 0.05337605126836238),
 (739, 0.0),
 (740, 0.06415002990995841),
 (741, 0.0),
 (742, 0.0),
 (743, 0.0),
 (744, 0.0),
 (745, 0.03774256780481986),
 (746, 0.0),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.0),
 (753, 0.0),
 (754, 0.040128617695256406),
 (755, 0.051434449987363975),
 (756, 0.0),
 (757, 0.0),
 (758, 0.1320196723968899),
 (759, 0.0),
 (760, 0.0),
 (761, 0.11547005383792516),
 (762, 0.051434449987363975),
 (763, 0.05802588531856595),
 (764, 0.0),
 (765, 0.03573708449459316),
 (766, 0.0),
 (767, 0.034020690871988585),
 (768, 0.025949964805384102),
 (769, 0.04667600280093366),
 (770, 0.0),
 (771, 0.0),
 (772, 0.04415107856883479),
 (773, 0.0),
 (774, 0.060858061945018464),
 (775, 0.0),
 (776, 0.0),
 (777, 0.0573775310549247),
 (778, 0.04303314829119352),
 (779, 0.033501260508640406),
 (780, 0.05802588531856595),
 (781, 0.0),
 (782, 0.059391387091649865),
 (783, 0.0),
 (784, 0.0),
 (785, 0.0),
 (786, 0.03253000243161777),
 (787, 0.0),
 (788, 0.06804138174397717),
 (789, 0.04303314829119352),
 (790, 0.02749286996141075),
 (791, 0.0),
 (792, 0.03703703703703704),
 (793, 0.0),
 (794, 0.0),
 (795, 0.0),
 (796, 0.0),
 (797, 0.10286889997472795),
 (798, 0.0),
 (799, 0.07332355751067665),
 (800, 0.0),
 (801, 0.07273929674533079),
 (802, 0.0),
 (803, 0.0),
 (804, 0.0),
 (805, 0.0),
 (806, 0.0),
 (807, 0.03703703703703704),
 (808, 0.05802588531856595),
 (809, 0.031219527052723135),
 (810, 0.0),
 (811, 0.030429030972509232),
 (812, 0.06011130897782883),
 (813, 0.03703703703703704),
 (814, 0.0),
 (815, 0.051899929610768204),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.036369648372665396),
 (820, 0.0),
 (821, 0.06851887098275317),
 (822, 0.07332355751067665),
 (823, 0.0),
 (824, 0.0),
 (825, 0.04667600280093366),
 (826, 0.048112522432468816),
 (827, 0.034020690871988585),
 (828, 0.0),
 (829, 0.0),
 (830, 0.0),
 (831, 0.029012942659282975),
 (832, 0.0),
 (833, 0.03573708449459316),
 (834, 0.0),
 (835, 0.06804138174397717),
 (836, 0.0),
 (837, 0.0),
 (838, 0.0),
 (839, 0.049690399499995326),
 (840, 0.04199605255658081),
 (841, 0.0),
 (842, 0.0842151921066519),
 (843, 0.0),
 (844, 0.0),
 (845, 0.022075539284417394),
 (846, 0.0),
 (847, 0.015167191839776335),
 (848, 0.0),
 (849, 0.04536092116265145),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (854, 0.07407407407407408),
 (855, 0.03513641844631533),
 (856, 0.0),
 (857, 0.0),
 (858, 0.0),
 (859, 0.0),
 (860, 0.018433375453644367),
 (861, 0.0),
 (862, 0.0),
 (863, 0.0),
 (864, 0.051899929610768204),
 (865, 0.0),
 (866, 0.0),
 (867, 0.04536092116265145),
 (868, 0.06415002990995841),
 (869, 0.0),
 (870, 0.032075014954979206),
 (871, 0.0),
 (872, 0.04415107856883479),
 (873, 0.030429030972509232),
 (874, 0.0),
 (875, 0.0),
 (876, 0.060858061945018464),
 (877, 0.04415107856883479),
 (878, 0.0),
 (879, 0.0),
 (880, 0.0),
 (881, 0.0),
 (882, 0.040128617695256406),
 (883, 0.0),
 (884, 0.0),
 (885, 0.0),
 (886, 0.0),
 (887, 0.022524579279982866),
 (888, 0.029012942659282975),
 (889, 0.0),
 (890, 0.03573708449459316),
 (891, 0.07856742013183862),
 (892, 0.07273929674533079),
 (893, 0.025269934785963444),
 (894, 0.0),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (899, 0.0),
 (900, 0.04199605255658081),
 (901, 0.0),
 (902, 0.0),
 (903, 0.04303314829119352),
 (904, 0.12655439943366653),
 (905, 0.0),
 (906, 0.04536092116265145),
 (907, 0.029695693545824933),
 (908, 0.0),
 (909, 0.032075014954979206),
 (910, 0.025490637096729087),
 (911, 0.0),
 (912, 0.055555555555555566),
 (913, 0.048112522432468816),
 (914, 0.0),
 (915, 0.030816677568068284),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0573775310549247),
 (919, 0.0),
 (920, 0.0),
 (921, 0.06327719971683327),
 (922, 0.0),
 (923, 0.05337605126836238),
 (924, 0.0),
 (925, 0.024640709031819096),
 (926, 0.034020690871988585),
 (927, 0.07856742013183862),
 (928, 0.0),
 (929, 0.0),
 (930, 0.06011130897782883),
 (931, 0.0),
 (932, 0.0),
 (933, 0.026948402781814772),
 (934, 0.04536092116265145),
 (935, 0.05337605126836238),
 (936, 0.0),
 (937, 0.0),
 (938, 0.0),
 (939, 0.04667600280093366),
 (940, 0.06011130897782883),
 (941, 0.0),
 (942, 0.03849001794597506),
 (943, 0.10206207261596575),
 (944, 0.0),
 (945, 0.0),
 (946, 0.032075014954979206),
 (947, 0.02151657414559676),
 (948, 0.0),
 (949, 0.024246432248443594),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.06243905410544627),
 (954, 0.0),
 (955, 0.0),
 (956, 0.03513641844631533),
 (957, 0.09335200560186732),
 (958, 0.0),
 (959, 0.07027283689263066),
 (960, 0.0),
 (961, 0.0),
 (962, 0.2321035412742638),
 (963, 0.0),
 (964, 0.0),
 (965, 0.03163859985841663),
 (966, 0.04415107856883479),
 (967, 0.0),
 (968, 0.03849001794597506),
 (969, 0.026435052857271473),
 (970, 0.0),
 (971, 0.0),
 (972, 0.04199605255658081),

In [68]:
sorted(list(enumerate(similarity(movie_index))),reverse=True,key=lambda x:x[1])[1:6]

TypeError: 'numpy.ndarray' object is not callable

In [85]:
def recommedate(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    similar_movies_with_scores = list(enumerate(distances))
    top_similar_movies = sorted(similar_movies_with_scores, reverse=True, key=lambda x: x[1])[1:6]
    
    
    for i in top_similar_movies:
        print(new_df.iloc[i[0]].title)

In [86]:
recommedate('Titanic')

Opal Dream
Under the Same Moon
The Switch
I Love You, Don't Touch Me!
Captain Phillips

In [90]:
i=(0,119)

In [91]:
new_df.iloc[i[1]]

movie_id                                                  272
title                                           Batman Begins
tags        driven tragedi , billionair bruce wayn dedic l...
Name: 119, dtype: object

In [92]:
new_df.iloc[i[1]].title

'Batman Begins'